---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-wave-test-a
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: sync-wave-test
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: wave
        value: "3"
    path: sync-wave-test
    repoURL: https://github.com/keiSunagawa/sync-wave-test.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-wave-test-b
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: sync-wave-test
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: wave
        value: "2"
    path: sync-wave-test
    repoURL: https://github.com/keiSunagawa/sync-wave-test.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-wave-test-c
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: sync-wave-test
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: wave
        value: "1"
    path: sync-wave-test
    repoURL: https://github.com/keiSunagawa/sync-wave-test.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true

