apiVersion: batch/v1
kind: Job
metadata:
  name: wait-job-{{ .Values.wave }}
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    annotations:
      argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: wait-jobs
        image: busybox:1.28
        command: ['sh', '-c', 'echo The app is running! && sleep 5']
      restartPolicy: Never
  backoffLimit: 0
